version: "3"
services:
  mysql:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./script/mysqlusers.sql:/docker-entrypoint-initdb.d/init.sql
