DROP DATABASE IF EXISTS oneid;
DROP USER IF EXISTS `oneidadmin`@`%`;
DROP USER IF EXISTS `oneiduser`@`%`;
CREATE DATABASE IF NOT EXISTS oneid CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `oneidadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `oneid`.* TO `oneidadmin`@`%`;
CREATE USER IF NOT EXISTS `oneiduser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `oneid`.* TO `oneiduser`@`%`;
FLUSH PRIVILEGES;